[package]
name = "mqtt-beacon"
version = "0.1.0"
authors = ["Oliver Cooper <oliver.cooper@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
rumqttc = "0.5.0"
btleplug = { version = "0.7.1", features = ["serde"] }
uuid = { version = "0.8", features = ["serde"] }